version: "3.7"

services:
  angular:
    build: ng-auth-app
    depends_on:
      - nest
    networks:
      - webnet
    ports:
      - "4200:4200"

  nest:
    build: nest-auth-app
    depends_on:
      - database
    networks:
      - webnet
    ports:
      - "8000:8000"

  database:
    image: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: "auth_app"
    restart: always
    networks:
      - webnet
    ports:
      - "8001:3306"

networks:
  webnet:
