http:
  host: 'localhost'
  port: 8000

db:
  mysql:
    type: 'mysql'
    host: 'localhost'
    port: 3306 
    database: 'auth_app'
    username: 'root'
    password: ''
    autoLoadEntities: true
    synchronize: true

auth:
  auth0:
    issuer: 'https://dev-v8y3pwd5.us.auth0.com/'
    audience: 'http://localhost:8000'
    domain: 'dev-v8y3pwd5.us.auth0.com'
    client:
      id: 'CYezkyAYZxjRU28JIsjE9zWWmA2p8Y2l'
      secret: 'pc2v4xr9810XC9klK9kinUkch8cQG-Sy8mtA0e1GFGZZH1odgAE3WI3htnQ1XHI3'

